name: Destroy Backend Infrastructure - nhyira

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./src/infraNhyira/moduleEc2

      - name: Terraform Plan Destroy
        run: terraform plan -destroy -out=tfplan -var "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}"
        working-directory: ./src/infraNhyira/moduleEc2

      - name: Verify Plan
        run: terraform show tfplan
        working-directory: ./src/infraNhyira/moduleEc2

      - name: Terraform Apply Destroy
        run: terraform apply -auto-approve tfplan
        working-directory: ./src/infraNhyira/moduleEc2

      - name: Verify Destruction
        run: terraform show
        working-directory: ./src/infraNhyira/moduleEc2